spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password: 123
    url: ""








springdoc:
  packages-to-scan: ##需要扫描的包,可以配置多个
    - com.yjy.codingmore.controller
  swagger-ui:
    enabled: true  #开启/禁止swagger,prod可以设置为false
    path: /swagger-ui.html  #swagger页面
  api-docs:
    enabled: true #开启/禁止api-docs, prod可以设置为false
    path: /api-docs #api的json文档
  use-management-port: false
